// NeoGears Product Database
// Comprehensive list of technology products

const PRODUCT_DATABASE = {
    // MOBITELI
    'iphone15pro': {
        id: 'iphone15pro',
        title: 'iPhone 15 Pro 128GB',
        category: 'MOBITELI',
        brand: 'Apple',
        currentPrice: '1.199,99 €',
        oldPrice: '1.399,99 €',
        image: 'https://aloalo.hr/upload/catalog/product/22683/1697647111_0903862.jpg',
        description: 'Najnoviji iPhone 15 Pro s A17 Pro čipom, titanijskim kućištem i naprednim kamerama. Dostupan u različitim bojama s 128GB prostora za pohranu.',
        specs: ['A17 Pro čip', 'Titanijsko kućište', '48MP kamera', '128GB memorija'],
        inStock: true,
        featured: true,
        badge: 'sale',
        badgeText: '-15%'
    },
    'iphone15': {
        id: 'iphone15',
        title: 'iPhone 15 128GB',
        category: 'MOBITELI',
        brand: 'Apple',
        currentPrice: '999,99 €',
        oldPrice: '',
        image: 'https://wowshop.hr/wp-content/uploads/2024/03/apple-iphone-15-pro-black-titanium-01-1000x1000.jpg',
        description: 'iPhone 15 s A16 Bionic čipom i Dynamic Island. Odličan izbor za svakodnevnu upotrebu.',
        specs: ['A16 Bionic čip', 'Dynamic Island', '48MP kamera', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxys24': {
        id: 'galaxys24',
        title: 'Samsung Galaxy S24 256GB',
        category: 'MOBITELI',
        brand: 'Samsung',
        currentPrice: '899,99 €',
        oldPrice: '',
        image: 'https://www.gsm-centar.hr/image/cache/catalog/LD0006099689_0006099728-1024x768.jpg',
        description: 'Samsung Galaxy S24 s najnovijim Snapdragon procesorom, odličnim kamerama i 256GB prostora.',
        specs: ['Snapdragon 8 Gen 3', '50MP kamera', '256GB memorija', 'AI funkcije'],
        inStock: true,
        featured: true,
        badge: 'new',
        badgeText: 'NOVO'
    },
    'galaxys24ultra': {
        id: 'galaxys24ultra',
        title: 'Samsung Galaxy S24 Ultra 512GB',
        category: 'MOBITELI',
        brand: 'Samsung',
        currentPrice: '1.399,99 €',
        oldPrice: '1.599,99 €',
        image: 'https://aloalo.hr/upload/catalog/product/23338/1706277899_0903913.jpg',
        description: 'Vrhunski Galaxy S24 Ultra s S Pen olovkom i 200MP kamerom.',
        specs: ['Snapdragon 8 Gen 3', '200MP kamera', 'S Pen', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'pixel8pro': {
        id: 'pixel8pro',
        title: 'Google Pixel 8 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Google',
        currentPrice: '799,99 €',
        oldPrice: '899,99 €',
        image: 'https://e-point.hr/wp-content/uploads/2024/01/HF15_BF4D7C5A-3EAD-43DF-A2C7-A14297C9E3C7_large.jpg',
        description: 'Google Pixel 8 Pro s Tensor G3 čipom i najnaprednijim AI funkcijama.',
        specs: ['Tensor G3 čip', 'AI fotografija', '50MP kamera', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'oneplus12': {
        id: 'oneplus12',
        title: 'OnePlus 12 256GB',
        category: 'MOBITELI',
        brand: 'OnePlus',
        currentPrice: '849,99 €',
        oldPrice: '',
        image: 'https://cdn.kalvo.com/uploads/img/gallery/57375-oneplus-12-2.jpg',
        description: 'OnePlus 12 s Snapdragon 8 Gen 3 čipom i brzim punjenjem.',
        specs: ['Snapdragon 8 Gen 3', '50MP kamera', '100W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'xiaomi14': {
        id: 'xiaomi14',
        title: 'Xiaomi 14 Pro 512GB',
        category: 'MOBITELI',
        brand: 'Xiaomi',
        currentPrice: '749,99 €',
        oldPrice: '849,99 €',
        image: 'https://www.univerzalno.com/uploads/images/xiaomi14-5_1738656075.webp',
        description: 'Xiaomi 14 Pro s Leica kamerama i premium dizajnom.',
        specs: ['Snapdragon 8 Gen 3', 'Leica kamere', '120W punjenje', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'huaweip60': {
        id: 'huaweip60',
        title: 'Huawei P60 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Huawei',
        currentPrice: '699,99 €',
        oldPrice: '',
        image: 'https://img.cdn-cnj.si/img/500/500/j6/j6BPEUoz8W.webp',
        description: 'Huawei P60 Pro s naprednim kamerama i elegantnim dizajnom.',
        specs: ['Kirin 9000S', '48MP kamera', 'Leica optika', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'sonyxperia1v': {
        id: 'sonyxperia1v',
        title: 'Sony Xperia 1 V 256GB',
        category: 'MOBITELI',
        brand: 'Sony',
        currentPrice: '1.199,99 €',
        oldPrice: '',
        image: 'https://media.icdn.hu/product/GalleryMod/2023-08/925931/resp/3030509_sony-xperia-1-v-65-5g-12-256gb-dualsim-fekete.webp',
        description: 'Sony Xperia 1 V s profesionalnim kamerama i 4K displayom.',
        specs: ['Snapdragon 8 Gen 2', '4K OLED display', 'Alpha kamere', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'iphone14pro': {
        id: 'iphone14pro',
        title: 'iPhone 14 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Apple',
        currentPrice: '1.099,99 €',
        oldPrice: '1.299,99 €',
        image: 'https://tehno-mag.hr/upload/catalog/product/17164/iphone-14-pro-128gb-gold_6319e6c1a6a03.jpg',
        description: 'iPhone 14 Pro s A16 Bionic čipom i Dynamic Island.',
        specs: ['A16 Bionic čip', 'Dynamic Island', '48MP Pro kamera', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxys23ultra': {
        id: 'galaxys23ultra',
        title: 'Samsung Galaxy S23 Ultra 512GB',
        category: 'MOBITELI',
        brand: 'Samsung',
        currentPrice: '1.299,99 €',
        oldPrice: '1.499,99 €',
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT-MQZDoxbUlj6ASsEtuhVrJVtsCV2ZY4KoA&s',
        description: 'Galaxy S23 Ultra s 200MP kamerom i S Pen olovkom.',
        specs: ['Snapdragon 8 Gen 2', '200MP kamera', 'S Pen uključen', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'pixel7pro': {
        id: 'pixel7pro',
        title: 'Google Pixel 7 Pro 128GB',
        category: 'MOBITELI',
        brand: 'Google',
        currentPrice: '649,99 €',
        oldPrice: '799,99 €',
        image: 'https://geniusmobile.lk/wp-content/uploads/2022/10/Google-Pixel-7-1.png',
        description: 'Google Pixel 7 Pro s Tensor G2 čipom i AI fotografijom.',
        specs: ['Tensor G2 čip', 'AI fotografija', '50MP kamera', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'oneplus11': {
        id: 'oneplus11',
        title: 'OnePlus 11 128GB',
        category: 'MOBITELI',
        brand: 'OnePlus',
        currentPrice: '699,99 €',
        oldPrice: '',
        image: 'https://oasis.opstatics.com/content/dam/oasis/page/2023/in/product/11/marble.png',
        description: 'OnePlus 11 s Snapdragon 8 Gen 2 i brzim punjenjem.',
        specs: ['Snapdragon 8 Gen 2', '50MP kamera', '100W punjenje', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'xiaomi13pro': {
        id: 'xiaomi13pro',
        title: 'Xiaomi 13 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Xiaomi',
        currentPrice: '799,99 €',
        oldPrice: '899,99 €',
        image: 'https://aloalo.hr/upload/catalog/product/23845/1711020876_0213663.jpg',
        description: 'Xiaomi 13 Pro s Leica kamerama i premium performansama.',
        specs: ['Snapdragon 8 Gen 2', 'Leica kamere', '120W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'oppofindn3': {
        id: 'oppofindn3',
        title: 'OPPO Find N3 512GB',
        category: 'MOBITELI',
        brand: 'OPPO',
        currentPrice: '1.599,99 €',
        oldPrice: '',
        image: 'https://tradingshenzhen.com/13668-large_default/oppo-find-n3-12gb512gb.jpg',
        description: 'Sklopivi OPPO Find N3 s Hasselblad kamerama.',
        specs: ['Snapdragon 8 Gen 2', 'Hasselblad kamere', 'Sklopivi dizajn', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'vivox100pro': {
        id: 'vivox100pro',
        title: 'Vivo X100 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Vivo',
        currentPrice: '899,99 €',
        oldPrice: '',
        image: 'https://www.electronic4you.hr/media/catalog/product/cache/7/image/1500x/9df78eab33525d08d6e5fb8d27136e95/2/4/248417.jpg',
        description: 'Vivo X100 Pro s MediaTek Dimensity 9300 čipom.',
        specs: ['MediaTek Dimensity 9300', '50MP kamera', 'Zeiss optika', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'honormagic6pro': {
        id: 'honormagic6pro',
        title: 'Honor Magic6 Pro 512GB',
        category: 'MOBITELI',
        brand: 'Honor',
        currentPrice: '1.099,99 €',
        oldPrice: '1.199,99 €',
        image: 'https://img02.honorfile.com/eu/uk/honor/pms/product/6936520836000/800_800_90Percent_44AAF69DFA4D8F309A9E66B241548152766C17BA70031D44mp.webp',
        description: 'Honor Magic6 Pro s naprednim AI funkcijama.',
        specs: ['Snapdragon 8 Gen 3', 'AI fotografija', '180MP kamera', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'nothingphone2': {
        id: 'nothingphone2',
        title: 'Nothing Phone (2) 256GB',
        category: 'MOBITELI',
        brand: 'Nothing',
        currentPrice: '649,99 €',
        oldPrice: '699,99 €',
        image: 'https://cdn.spectrum-international.fr/_/rs:fit:800:800/ex:1/bG9jYWw6Ly8vL2Vjb21tZXJjZS9wcm9kdWN0cy9ieS1jYXRhbG9nL2NhdGFsb2ctMC9lYW4vNi85LzcvNC82OTc0NDM0MjIwOTgwLmpwZw.jpg',
        description: 'Nothing Phone (2) s jedinstvenim Glyph sučeljem.',
        specs: ['Snapdragon 8+ Gen 1', 'Glyph Interface', '50MP kamera', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'realme11pro': {
        id: 'realme11pro',
        title: 'Realme 11 Pro+ 256GB',
        category: 'MOBITELI',
        brand: 'Realme',
        currentPrice: '549,99 €',
        oldPrice: '649,99 €',
        image: 'https://initiative.co.in/wp-content/uploads/2024/02/Untitled-design-70.jpg',
        description: 'Realme 11 Pro+ s MediaTek Dimensity 7050 čipom.',
        specs: ['MediaTek Dimensity 7050', '200MP kamera', '100W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'redminotepro': {
        id: 'redminotepro',
        title: 'Redmi Note 13 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Xiaomi',
        currentPrice: '399,99 €',
        oldPrice: '449,99 €',
        image: 'https://aloalo.hr/upload/catalog/product/23315/1706083411_0213635.jpg',
        description: 'Redmi Note 13 Pro s odličnim omjerom cijene i performansi.',
        specs: ['Snapdragon 7s Gen 2', '200MP kamera', '67W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },

    // LAPTOPI
    'macbookair': {
        id: 'macbookair',
        title: 'MacBook Air M3 13" 256GB',
        category: 'LAPTOPI',
        brand: 'Apple',
        currentPrice: '1.349,99 €',
        oldPrice: '1.499,99 €',
        image: 'https://media.wired.com/photos/65ea34d70264b0ad869cbc18/master/w_2560%2Cc_limit/MacBook-Air-M3-Review-Featured-Gear.jpg',
        description: 'MacBook Air s M3 čipom pruža nevjerojatnu performansu i bateriju koja traje cijeli dan.',
        specs: ['M3 čip', '13.6" Liquid Retina', '256GB SSD', '18h baterija'],
        inStock: true,
        featured: true,
        badge: 'sale',
        badgeText: '-10%'
    },
    'macbookpro': {
        id: 'macbookpro',
        title: 'MacBook Pro M3 Pro 14" 512GB',
        category: 'LAPTOPI',
        brand: 'Apple',
        currentPrice: '2.199,99 €',
        oldPrice: '',
        image: 'https://cdn.mos.cms.futurecdn.net/CBQdQAHgggtdo66eddi5yU.jpg',
        description: 'Profesionalni MacBook Pro s M3 Pro čipom za zahtjevne zadatke.',
        specs: ['M3 Pro čip', '14.2" Liquid Retina XDR', '512GB SSD', 'ProRes podrška'],
        inStock: true,
        featured: false
    },
    'dellxps13': {
        id: 'dellxps13',
        title: 'Dell XPS 13 Intel i7 512GB',
        category: 'LAPTOPI',
        brand: 'Dell',
        currentPrice: '1.299,99 €',
        oldPrice: '1.499,99 €',
        image: 'https://pictures-nigeria.jijistatic.net/153666408_NjIwLTc1My1lZGNlYjg4MmIy.webp',
        description: 'Elegantan Dell XPS 13 s Intel Core i7 procesorom i premium dizajnom.',
        specs: ['Intel Core i7', '13.4" InfinityEdge', '512GB SSD', '16GB RAM'],
        inStock: true,
        featured: false
    },
    'lenovothinkpad': {
        id: 'lenovothinkpad',
        title: 'Lenovo ThinkPad X1 Carbon Gen 11',
        category: 'LAPTOPI',
        brand: 'Lenovo',
        currentPrice: '1.599,99 €',
        oldPrice: '',
        image: 'https://cdn.mos.cms.futurecdn.net/gwCVccweaX2Xt6X3CxyGuP.jpg',
        description: 'Poslovni laptop s vrhunskim performansama i dugotrajnom baterijom.',
        specs: ['Intel Core i7', '14" WUXGA', '1TB SSD', 'TrackPoint'],
        inStock: true,
        featured: false
    },
    'hpspectre': {
        id: 'hpspectre',
        title: 'HP Spectre x360 14" Intel i7',
        category: 'LAPTOPI',
        brand: 'HP',
        currentPrice: '1.399,99 €',
        oldPrice: '1.599,99 €',
        image: 'https://www.notebookcheck.net/fileadmin/_processed_/8/2/csm_IMG_2120_22dba18202.jpg',
        description: 'Konvertibilni laptop s OLED displayom i premium dizajnom.',
        specs: ['Intel Core i7', '14" OLED touchscreen', '512GB SSD', '360° okretanje'],
        inStock: true,
        featured: false
    },
    'asuszenbook': {
        id: 'asuszenbook',
        title: 'ASUS ZenBook 14 OLED',
        category: 'LAPTOPI',
        brand: 'ASUS',
        currentPrice: '1.199,99 €',
        oldPrice: '',
        image: 'https://pcchip.hr/wp-content/uploads/2024/05/11.webp',
        description: 'Elegantan ultrabook s OLED displayom i AMD Ryzen procesorom.',
        specs: ['AMD Ryzen 7', '14" OLED 2.8K', '512GB SSD', 'NumberPad 2.0'],
        inStock: true,
        featured: false
    },
    'surfacelaptop': {
        id: 'surfacelaptop',
        title: 'Microsoft Surface Laptop 5 13.5"',
        category: 'LAPTOPI',
        brand: 'Microsoft',
        currentPrice: '1.299,99 €',
        oldPrice: '',
        image: 'https://www.pcworld.com/wp-content/uploads/2025/04/Surface-Laptop-5-primary.jpg?quality=50&strip=all',
        description: 'Premium laptop s touchscreen displayom i Alcantara tipkovnicom.',
        specs: ['Intel Core i7', '13.5" PixelSense', '512GB SSD', 'Alcantara tipkovnica'],
        inStock: true,
        featured: false
    },
    'macbookpro16': {
        id: 'macbookpro16',
        title: 'MacBook Pro M3 Max 16" 1TB',
        category: 'LAPTOPI',
        brand: 'Apple',
        currentPrice: '3.199,99 €',
        oldPrice: '3.499,99 €',
        image: 'https://cdn.arstechnica.net/wp-content/uploads/2023/11/IMG_1415.jpeg',
        description: 'Najmoćniji MacBook Pro s M3 Max čipom za profesionalce.',
        specs: ['M3 Max čip', '16.2" Liquid Retina XDR', '1TB SSD', '36-core GPU'],
        inStock: true,
        featured: false
    },
    'alienwarex17': {
        id: 'alienwarex17',
        title: 'Alienware x17 R2 RTX 4080',
        category: 'LAPTOPI',
        brand: 'Dell',
        currentPrice: '2.899,99 €',
        oldPrice: '',
        image: 'https://www.notebookcheck.net/fileadmin/Notebooks/News/_nc3/alienware_x16_6.jpg',
        description: 'Gaming laptop s RTX 4080 i 360Hz displayom.',
        specs: ['Intel Core i9', 'RTX 4080', '17.3" 360Hz', '1TB SSD'],
        inStock: true,
        featured: false
    },
    'asusrogzephyrus': {
        id: 'asusrogzephyrus',
        title: 'ASUS ROG Zephyrus G16 RTX 4070',
        category: 'LAPTOPI',
        brand: 'ASUS',
        currentPrice: '2.199,99 €',
        oldPrice: '2.399,99 €',
        image: 'https://assets-prd.ignimgs.com/2024/10/14/desktop-1728941786788.jpg',
        description: 'Tanki gaming laptop s RTX 4070 i OLED displayom.',
        specs: ['AMD Ryzen 9', 'RTX 4070', '16" OLED 240Hz', '1TB SSD'],
        inStock: true,
        featured: false
    },
    'lenovoyoga9i': {
        id: 'lenovoyoga9i',
        title: 'Lenovo Yoga 9i 14" 2-in-1',
        category: 'LAPTOPI',
        brand: 'Lenovo',
        currentPrice: '1.699,99 €',
        oldPrice: '1.899,99 €',
        image: 'https://www.cnet.com/a/img/resize/7c0d3d0b074edd16860b2d2bd6ce1560147f45a1/hub/2024/09/27/08266f88-a165-42a6-af66-0d611c6641e1/lenovo-yoga-9i-14-gen-9-overview.jpg?auto=webp&fit=crop&height=900&precrop=3782,2842,x554,y0&width=1200',
        description: 'Konvertibilni laptop s OLED touchscreen displayom.',
        specs: ['Intel Core i7', '14" OLED touchscreen', '1TB SSD', '360° okretanje'],
        inStock: true,
        featured: false
    },
    'razerblade15': {
        id: 'razerblade15',
        title: 'Razer Blade 15 RTX 4060',
        category: 'LAPTOPI',
        brand: 'Razer',
        currentPrice: '1.999,99 €',
        oldPrice: '',
        image: 'https://img.leboncoin.fr/api/v1/lbcpb1/images/90/41/f3/9041f3e09b6acc7d31dc68d84ae1b225402a8a0f.jpg?rule=ad-large',
        description: 'Kompaktni gaming laptop s premium dizajnom.',
        specs: ['Intel Core i7', 'RTX 4060', '15.6" QHD 240Hz', '1TB SSD'],
        inStock: true,
        featured: false
    },

    // TABLETI
    'ipadpro': {
        id: 'ipadpro',
        title: 'iPad Pro 11" M4 256GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '1.099,99 €',
        oldPrice: '',
        image: 'https://media.pazar3.mk/Image/43bc20ca-c48b-4c81-b5c4-0d2d2ecefeb5/20250531/false/false/1280/960/ipad-pro-m4-256gb-11.jpeg?noLogo=true',
        description: 'iPad Pro s M4 čipom i Liquid Retina displayom. Idealan za profesionalce.',
        specs: ['M4 čip', '11" Liquid Retina', 'Apple Pencil podrška', '256GB memorija'],
        inStock: true,
        featured: true,
        badge: 'bestseller',
        badgeText: 'BESTSELLER'
    },
    'ipadair': {
        id: 'ipadair',
        title: 'iPad Air M2 10.9" 128GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '699,99 €',
        oldPrice: '799,99 €',
        image: 'https://www.zdnet.com/a/img/2024/05/23/0ba06652-4cdf-4525-b7ce-efcb4b0de055/4.jpg',
        description: 'iPad Air s M2 čipom - savršen balans performansi i cijene.',
        specs: ['M2 čip', '10.9" Liquid Retina', 'Touch ID', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxytabs9': {
        id: 'galaxytabs9',
        title: 'Samsung Galaxy Tab S9 256GB',
        category: 'TABLETI',
        brand: 'Samsung',
        currentPrice: '899,99 €',
        oldPrice: '',
        image: 'https://images.samsung.com/is/image/samsung/p6pim/hr/sm-x926bzareue/gallery/hr-galaxy-tab-s10-ultra-sm-x920-524353-sm-x926bzareue-thumb-543700308?$UX_EXT1_PNG$',
        description: 'Premium Android tablet s S Pen olovkom i AMOLED displayom.',
        specs: ['Snapdragon 8 Gen 2', '11" AMOLED', 'S Pen uključen', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'ipadmini': {
        id: 'ipadmini',
        title: 'iPad mini 6th gen 256GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '649,99 €',
        oldPrice: '749,99 €',
        image: 'https://u-mercari-images.mercdn.net/photos/m99263229786_1.jpg',
        description: 'Kompaktni iPad s A15 Bionic čipom i Apple Pencil podrškom.',
        specs: ['A15 Bionic čip', '8.3" Liquid Retina', 'Apple Pencil 2', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'surfacepro9': {
        id: 'surfacepro9',
        title: 'Microsoft Surface Pro 9 256GB',
        category: 'TABLETI',
        brand: 'Microsoft',
        currentPrice: '1.199,99 €',
        oldPrice: '',
        image: 'https://media.cnn.com/api/v1/images/stellar/prod/microsoft-surface-pro-2024-cnnu-01.jpg?c=original',
        description: '2-u-1 tablet s Intel procesorom i detachable tipkovnicom.',
        specs: ['Intel Core i5', '13" PixelSense', 'Type Cover', '256GB SSD'],
        inStock: true,
        featured: false
    },
    'lenovotab': {
        id: 'lenovotab',
        title: 'Lenovo Tab P12 Pro 256GB',
        category: 'TABLETI',
        brand: 'Lenovo',
        currentPrice: '599,99 €',
        oldPrice: '699,99 €',
        image: 'https://www.bug.hr/img/lenovo-tab-p12-pro-i-tab-p11-5g-tableti-za-profesionalne-i-kucne-korisnike_CAOxGz.png',
        description: 'Android tablet s OLED displayom i Precision Pen 3.',
        specs: ['MediaTek Dimensity 9000', '12.6" OLED', 'Precision Pen 3', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'ipadpro129': {
        id: 'ipadpro129',
        title: 'iPad Pro 12.9" M4 512GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '1.499,99 €',
        oldPrice: '1.699,99 €',
        image: 'https://m-cdn.phonearena.com/images/hub/268-wide-two_1200/Apple-iPad-Pro-M4-2024-release-date-pricing-features-and-specs.jpg',
        description: 'Najveći iPad Pro s M4 čipom i Liquid Retina XDR displayom.',
        specs: ['M4 čip', '12.9" Liquid Retina XDR', 'Apple Pencil Pro', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxytabs9ultra': {
        id: 'galaxytabs9ultra',
        title: 'Samsung Galaxy Tab S9 Ultra 512GB',
        category: 'TABLETI',
        brand: 'Samsung',
        currentPrice: '1.299,99 €',
        oldPrice: '',
        image: 'https://static1.anpoimages.com/wordpress/wp-content/uploads/2023/08/samsung-galaxy-tab-s9-ultra-plants.jpg',
        description: 'Najveći Galaxy tablet s 14.6" AMOLED displayom.',
        specs: ['Snapdragon 8 Gen 2', '14.6" AMOLED', 'S Pen uključen', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'surfacepro10': {
        id: 'surfacepro10',
        title: 'Microsoft Surface Pro 10 512GB',
        category: 'TABLETI',
        brand: 'Microsoft',
        currentPrice: '1.599,99 €',
        oldPrice: '',
        image: 'https://i0.wp.com/www.tabletblog.de/wp-content/uploads/2024/05/microsoft-surface-pro-10-business-windows-11.jpg?fit=2500%2C1667&ssl=1',
        description: 'Najnoviji Surface Pro s Intel Core Ultra procesorom.',
        specs: ['Intel Core Ultra 7', '13" PixelSense Flow', 'Type Cover Pro', '512GB SSD'],
        inStock: true,
        featured: false
    },

    // GAMING
    'ps5': {
        id: 'ps5',
        title: 'PlayStation 5 Console',
        category: 'GAMING',
        brand: 'Sony',
        currentPrice: '549,99 €',
        oldPrice: '',
        image: 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/21990370/vpavic_4261_20201023_0058.jpg?quality=90&strip=all&crop=0,0,100,100',
        description: 'Najnovija PlayStation 5 konzola s ultra-brzim SSD-om.',
        specs: ['Custom AMD Zen 2', '825GB SSD', '4K gaming', 'Ray tracing'],
        inStock: true,
        featured: false
    },
    'xboxseriesx': {
        id: 'xboxseriesx',
        title: 'Xbox Series X Console',
        category: 'GAMING',
        brand: 'Microsoft',
        currentPrice: '499,99 €',
        oldPrice: '549,99 €',
        image: 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/21916918/twarren_xboxseriesxhandson.jpg?quality=90&strip=all&crop=0,0,100,100',
        description: 'Moćna Xbox Series X konzola za 4K gaming.',
        specs: ['Custom AMD Zen 2', '1TB SSD', '4K 120fps', 'Quick Resume'],
        inStock: true,
        featured: false
    },
    'steamdeck': {
        id: 'steamdeck',
        title: 'Steam Deck 512GB',
        category: 'GAMING',
        brand: 'Valve',
        currentPrice: '679,99 €',
        oldPrice: '',
        image: 'https://www.njuskalo.hr/image-w920x690/igrace-konzole/steam-deck-512gb-slika-232462052.jpg',
        description: 'Prijenosna gaming konzola s pristupom Steam biblioteci.',
        specs: ['AMD APU', '7" touchscreen', '512GB SSD', 'SteamOS'],
        inStock: true,
        featured: false
    },
    'nintendoswitch': {
        id: 'nintendoswitch',
        title: 'Nintendo Switch OLED 64GB',
        category: 'GAMING',
        brand: 'Nintendo',
        currentPrice: '349,99 €',
        oldPrice: '',
        image: 'https://youget.pt/67824-large_default/console-nintendo-switch-oled-version-64gb-bluered.jpg',
        description: 'Hibridna gaming konzola s OLED displayom.',
        specs: ['NVIDIA Tegra X1', '7" OLED touchscreen', '64GB memorija', 'Joy-Con kontroleri'],
        inStock: true,
        featured: false
    },
    'asusrog': {
        id: 'asusrog',
        title: 'ASUS ROG Ally Z1 Extreme',
        category: 'GAMING',
        brand: 'ASUS',
        currentPrice: '799,99 €',
        oldPrice: '899,99 €',
        image: 'https://maiacombo.com/cdn/shop/files/ASUS-ROG-Ally-Z1-Skin-Wrap-Blue-Art_1080x.jpg?v=1705742511',
        description: 'Windows gaming handheld s AMD Z1 Extreme čipom.',
        specs: ['AMD Z1 Extreme', '7" FHD 120Hz', '512GB SSD', 'Windows 11'],
        inStock: true,
        featured: false
    },
    'logitechg923': {
        id: 'logitechg923',
        title: 'Logitech G923 Racing Wheel',
        category: 'GAMING',
        brand: 'Logitech',
        currentPrice: '399,99 €',
        oldPrice: '',
        image: 'https://media.icdn.hu/product/GalleryMod/2023-05/906379/resp/2182024_logitech-g923-trueforce-verseny-kormany-es-pedal-pc-playstation-fekete.webp',
        description: 'Profesionalni racing volan s TRUEFORCE tehnologijom.',
        specs: ['TRUEFORCE feedback', 'Dual clutch', 'Leather wrap', 'PS5/Xbox/PC kompatibilnost'],
        inStock: true,
        featured: false
    },

    // DODACI
    'airpodspro': {
        id: 'airpodspro',
        title: 'Apple AirPods Pro (3rd gen)',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '279,99 €',
        oldPrice: '329,99 €',
        image: 'https://down-br.img.susercontent.com/file/br-11134207-7r98o-lttp9f8r2f5522',
        description: 'Bežične slušalice s aktivnim poništavanjem buke.',
        specs: ['Active Noise Cancellation', 'Spatial Audio', 'H2 čip', 'MagSafe punjenje'],
        inStock: true,
        featured: false
    },
    'applewatch': {
        id: 'applewatch',
        title: 'Apple Watch Series 9 45mm',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '449,99 €',
        oldPrice: '',
        image: 'https://www.otterbox.com/dw/image/v2/BGMS_PRD/on/demandware.static/-/Sites-masterCatalog/default/dw1f2d2bf5/productimages/dis/cases-screen-protection/watch-case-series-7-45mm/watch-case-series-7-45mm-fine-timing-1.png?sw=800&sh=800',
        description: 'Najnapredniji Apple Watch s S9 čipom.',
        specs: ['S9 SiP čip', '45mm Always-On Retina', 'GPS + Cellular', 'Zdravstveni senzori'],
        inStock: true,
        featured: false
    },
    'magickeyboard': {
        id: 'magickeyboard',
        title: 'Apple Magic Keyboard',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '119,99 €',
        oldPrice: '139,99 €',
        image: 'https://macshack.co.za/cdn/shop/files/IMG_9062.heic?v=1705925533&width=1946',
        description: 'Bežična tipkovnica s Touch ID senzorem.',
        specs: ['Touch ID', 'Bežična povezanost', 'Punjiva baterija', 'Scissor mehanizam'],
        inStock: true,
        featured: false
    },
    'magicmouse': {
        id: 'magicmouse',
        title: 'Apple Magic Mouse',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '89,99 €',
        oldPrice: '',
        image: 'https://i.ebayimg.com/images/g/BBoAAOSwP8hk5Xed/s-l1200.jpg',
        description: 'Bežični miš s Multi-Touch površinom.',
        specs: ['Multi-Touch površina', 'Bežična povezanost', 'Punjiva baterija', 'Ergonomski dizajn'],
        inStock: true,
        featured: false
    },
    'samsungbuds': {
        id: 'samsungbuds',
        title: 'Samsung Galaxy Buds2 Pro',
        category: 'DODACI',
        brand: 'Samsung',
        currentPrice: '199,99 €',
        oldPrice: '229,99 €',
        image: 'https://images.samsung.com/ph/galaxy-buds2-pro/feature/galaxy-buds2-pro-easy-pairing-front-mo.jpg',
        description: 'Premium bežične slušalice s ANC tehnologijom.',
        specs: ['Active Noise Cancellation', '360 Audio', 'IPX7 otpornost', 'Bežično punjenje'],
        inStock: true,
        featured: false
    },
    'logitechmx': {
        id: 'logitechmx',
        title: 'Logitech MX Master 3S',
        category: 'DODACI',
        brand: 'Logitech',
        currentPrice: '109,99 €',
        oldPrice: '',
        image: 'https://s3.wasabisys.com/labs-web-static-assets/product-admin/1732825654114-Logitech--Mx%20Master%203s.png',
        description: 'Profesionalni bežični miš za produktivnost.',
        specs: ['4000 DPI senzor', 'USB-C punjenje', 'Multi-device', 'Ergonomski dizajn'],
        inStock: true,
        featured: false
    },
    'ankercharger': {
        id: 'ankercharger',
        title: 'Anker PowerPort III 65W',
        category: 'DODACI',
        brand: 'Anker',
        currentPrice: '49,99 €',
        oldPrice: '59,99 €',
        image: 'https://cdn.supercommerce.io/etisal-store/uploads/anker-powerport-iii-2-port-60w-_-black-1-1.jpg',
        description: 'Brzi USB-C punjač za laptop i mobitel.',
        specs: ['65W izlaz', 'GaN tehnologija', 'USB-C PD', 'Kompaktni dizajn'],
        inStock: true,
        featured: false
    },
    'belkinstand': {
        id: 'belkinstand',
        title: 'Belkin MagSafe 3-in-1 Charger',
        category: 'DODACI',
        brand: 'Belkin',
        currentPrice: '149,99 €',
        oldPrice: '',
        image: 'https://storage.googleapis.com/bionic_1626848719/products/a81632e372f57bc73e7d379e2ae08cfea1e0d132/banners/14002101_1685637769.jpg',
        description: 'Bežični punjač za iPhone, Apple Watch i AirPods.',
        specs: ['MagSafe kompatibilnost', '15W bežično punjenje', 'Apple Watch punjač', 'AirPods punjač'],
        inStock: true,
        featured: false
    },
    'usbchub': {
        id: 'usbchub',
        title: 'USB-C Hub 7-in-1',
        category: 'DODACI',
        brand: 'HyperDrive',
        currentPrice: '79,99 €',
        oldPrice: '99,99 €',
        image: 'https://m.media-amazon.com/images/I/61DIZ7Qh0wL.jpg',
        description: 'Multifunkcionalni USB-C hub s 7 portova.',
        specs: ['7 portova', '4K HDMI izlaz', 'USB 3.0', 'SD card čitač'],
        inStock: true,
        featured: false
    },
    'webcam4k': {
        id: 'webcam4k',
        title: 'Logitech Brio 4K Webcam',
        category: 'DODACI',
        brand: 'Logitech',
        currentPrice: '199,99 €',
        oldPrice: '',
        image: 'https://www.pmctelecom.co.uk/media/catalog/product/cache/b730fd02e7e4cc6702d38a905f701ad8/m/x/mx_brio_705_in_box.webp',
        description: '4K Ultra HD webcam za profesionalne video pozive.',
        specs: ['4K Ultra HD', 'HDR podrška', 'Auto focus', 'Windows Hello'],
        inStock: true,
        featured: false
    },
    'portablessd': {
        id: 'portablessd',
        title: 'Samsung T7 Portable SSD 1TB',
        category: 'DODACI',
        brand: 'Samsung',
        currentPrice: '129,99 €',
        oldPrice: '149,99 €',
        image: 'https://globaliraq.net/cdn/shop/files/4_5459f337-318a-4bdd-b992-22c293b419d1_2048x.jpg?v=1727593796',
        description: 'Brzi prijenosni SSD s USB 3.2 sučeljem.',
        specs: ['1TB kapacitet', '1050 MB/s brzina', 'USB 3.2 Gen 2', 'Kompaktni dizajn'],
        inStock: true,
        featured: false
    },
    'bluetoothspeaker': {
        id: 'bluetoothspeaker',
        title: 'JBL Charge 5 Bluetooth Speaker',
        category: 'DODACI',
        brand: 'JBL',
        currentPrice: '179,99 €',
        oldPrice: '',
        image: 'https://www.cloveandtwine.com/cdn/shop/files/custom-jbl-charge-5-portable-bluetooth-speaker-technology-30240419545176_1445x.jpg?v=1684230544',
        description: 'Vodootporni Bluetooth zvučnik s powerbank funkcijom.',
        specs: ['IP67 otpornost', '20h baterija', 'Powerbank funkcija', 'JBL Pro Sound'],
        inStock: true,
        featured: false
    },
    'applepen': {
        id: 'applepen',
        title: 'Apple Pencil (2nd generation)',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '139,99 €',
        oldPrice: '149,99 €',
        image: 'https://www.zdnet.com/a/img/resize/0067a29590a8f048635ae577402135825b690b74/2024/03/29/7ea616c5-15a6-4f6c-bb69-ee5f55e2021c/img-1321.jpg?auto=webp&fit=crop&height=1200&width=1200',
        description: 'Precizna olovka za iPad s magnetskim punjenjem.',
        specs: ['Magnetsko punjenje', 'Pixel-perfect preciznost', 'Tilt i pressure senzori', 'Double-tap funkcija'],
        inStock: true,
        featured: false
    },
    'sonyheadphones': {
        id: 'sonyheadphones',
        title: 'Sony WH-1000XM5 Headphones',
        category: 'DODACI',
        brand: 'Sony',
        currentPrice: '399,99 €',
        oldPrice: '449,99 €',
        image: 'https://www.stuff.tv/wp-content/uploads/sites/2/2022/06/IMG_5175.jpg?w=1080',
        description: 'Premium noise-cancelling slušalice s 30h baterijom.',
        specs: ['Industry-leading ANC', '30h baterija', 'LDAC codec', 'Multipoint povezivanje'],
        inStock: true,
        featured: false
    },
    'razerdeathstalker': {
        id: 'razerdeathstalker',
        title: 'Razer DeathStalker V2 Pro',
        category: 'DODACI',
        brand: 'Razer',
        currentPrice: '249,99 €',
        oldPrice: '',
        image: 'https://static1.pocketlintimages.com/wordpress/wp-content/uploads/wm/162606-gadgets-review-razer-deathstalker-v2-pro-tkl-review-image7-kngqczlfmg.jpg',
        description: 'Bežična gaming tipkovnica s low-profile switchevima.',
        specs: ['Low-profile optical switches', 'HyperSpeed Wireless', '90h baterija', 'RGB Chroma'],
        inStock: true,
        featured: false
    },
    'corsairram': {
        id: 'corsairram',
        title: 'Corsair Vengeance LPX 32GB DDR4',
        category: 'DODACI',
        brand: 'Corsair',
        currentPrice: '129,99 €',
        oldPrice: '159,99 €',
        image: 'https://www.links.hr/images/thumbs/0210180_memorija-pc4-41600-16gb-corsair-vengeance-cmk16gx5m2b5200z40-ddr5-5200mhz-2x8gb-kit-010504430_415.jpg',
        description: 'High-performance DDR4 memorija za gaming i rad.',
        specs: ['32GB (2x16GB)', 'DDR4-3200', 'Low profile design', 'XMP 2.0 podrška'],
        inStock: true,
        featured: false
    },
    'nvidiartx4070': {
        id: 'nvidiartx4070',
        title: 'NVIDIA GeForce RTX 4070 12GB',
        category: 'DODACI',
        brand: 'NVIDIA',
        currentPrice: '649,99 €',
        oldPrice: '699,99 €',
        image: 'https://www.tonerpartner.hr/userdata/products/1427/3524759-6523e4bb4b4fc.jpg',
        description: 'Moćna grafička kartica za 1440p gaming i kreativnost.',
        specs: ['Ada Lovelace arhitektura', '12GB GDDR6X', 'DLSS 3', 'Ray Tracing 3rd gen'],
        inStock: true,
        featured: false
    },
    'monitorlg': {
        id: 'monitorlg',
        title: 'LG UltraGear 27" 4K Gaming Monitor',
        category: 'DODACI',
        brand: 'LG',
        currentPrice: '599,99 €',
        oldPrice: '',
        image: 'https://www.tradeinn.com/f/14044/140444174_9/lg-27gp95rp-b-27-4k-ips-led-160hz-gaming-monitor.webp',
        description: '4K gaming monitor s 144Hz refresh rate i HDR600.',
        specs: ['27" 4K IPS', '144Hz refresh rate', 'HDR600', 'G-Sync Compatible'],
        inStock: true,
        featured: false
    },

    // Dodatni MOBITELI
    'motorolaedge40': {
        id: 'motorolaedge40',
        title: 'Motorola Edge 40 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Motorola',
        currentPrice: '599,99 €',
        oldPrice: '699,99 €',
        image: 'https://bukal.hr/wp-content/uploads/2025/05/motorola-edge-40-neo-12-gb-256-gb-soothing-sea-71975_1.jpg',
        description: 'Motorola Edge 40 Pro s Snapdragon 8 Gen 2 čipom.',
        specs: ['Snapdragon 8 Gen 2', '50MP kamera', '125W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'fairphone5': {
        id: 'fairphone5',
        title: 'Fairphone 5 256GB',
        category: 'MOBITELI',
        brand: 'Fairphone',
        currentPrice: '699,99 €',
        oldPrice: '',
        image: 'https://www.nabava.net/slike/products/29/99/49709929/nekategorizirano-fairphone-5-5g-dual-sim-8gb-256gb-sky-blue-android-130-smartphone_ab06e01d.jpeg',
        description: 'Održivi smartphone s modularnim dizajnom.',
        specs: ['QCM6490 čip', '50MP kamera', 'Modularan dizajn', '256GB memorija'],
        inStock: true,
        featured: false
    },

    // Dodatni LAPTOPI
    'frameworklaptop': {
        id: 'frameworklaptop',
        title: 'Framework Laptop 13" Intel i7',
        category: 'LAPTOPI',
        brand: 'Framework',
        currentPrice: '1.399,99 €',
        oldPrice: '',
        image: 'https://dv9dhd03d71d4.cloudfront.net/eyJidWNrZXQiOiJwcm9kLXd3dy1hc3NldHMtcGVyZmVjdHJlYyIsImtleSI6ImltYWdlcy9wcm9kdWN0cy9sYXB0b3BzL1BlcmZlY3RSZWNfTGFwdG9wX0ZyYW1ld29ya19MYXB0b3AxMy5wbmciLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjYwMCwiZml0IjoiY292ZXIifX19',
        description: 'Modularan laptop koji možete sami popraviti i nadograditi.',
        specs: ['Intel Core i7', '13.5" 2256x1504', 'Modularni portovi', '512GB SSD'],
        inStock: true,
        featured: false
    },
    'steamdeckoled': {
        id: 'steamdeckoled',
        title: 'Steam Deck 512GB OLED',
        category: 'GAMING',
        brand: 'Valve',
        currentPrice: '679,99 €',
        oldPrice: '',
        image: 'https://www.tccq.com/image/cache/catalog/0201007/Steam%20Deck%20Console%20512GB%20(OLED)%20(5)-600x600.jpg',
        description: 'Prijenosna gaming konzola s OLED displayom.',
        specs: ['AMD APU', '7.4" OLED HDR', 'SteamOS', '512GB NVMe'],
        inStock: true,
        featured: true,
        badge: 'new',
        badgeText: 'NOVO'
    },

    // Dodatni TABLETI
    'galaxytaba9': {
        id: 'galaxytaba9',
        title: 'Samsung Galaxy Tab A9+ 128GB',
        category: 'TABLETI',
        brand: 'Samsung',
        currentPrice: '299,99 €',
        oldPrice: '349,99 €',
        image: 'https://media.cashconverters.co.za/wp-content/uploads/2025/05/CAWMD030462-1982216-1.webp',
        description: 'Pristupačan Android tablet za svakodnevnu upotrebu.',
        specs: ['Helio G99', '11" LCD', 'Quad speakers', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'huaweimatepadt11': {
        id: 'huaweimatepadt11',
        title: 'Huawei MatePad T11 128GB',
        category: 'TABLETI',
        brand: 'Huawei',
        currentPrice: '249,99 €',
        oldPrice: '',
        image: 'https://images.prom.ua/3825011596_w1280_h640_planshet-huawei-matepad.jpg',
        description: 'Huawei tablet s HarmonyOS sustavom.',
        specs: ['Snapdragon 662', '10.95" IPS', 'HarmonyOS', '128GB memorija'],
        inStock: true,
        featured: false
    }
};

// Helper functions
function getProductsByCategory(category) {
    return Object.values(PRODUCT_DATABASE).filter(product =>
        product.category === category.toUpperCase()
    );
}

function getFeaturedProducts() {
    return Object.values(PRODUCT_DATABASE).filter(product => product.featured);
}

function searchProducts(searchTerm) {
    const term = searchTerm.toLowerCase();
    return Object.values(PRODUCT_DATABASE).filter(product =>
        product.title.toLowerCase().includes(term) ||
        product.description.toLowerCase().includes(term) ||
        product.brand.toLowerCase().includes(term) ||
        product.category.toLowerCase().includes(term)
    );
}

function getProductById(id) {
    return PRODUCT_DATABASE[id] || null;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        PRODUCT_DATABASE,
        getProductsByCategory,
        getFeaturedProducts,
        searchProducts,
        getProductById
    };
}
