// TechShop Product Database
// Comprehensive list of technology products

const PRODUCT_DATABASE = {
    // MOBITELI
    'iphone15pro': {
        id: 'iphone15pro',
        title: 'iPhone 15 Pro 128GB',
        category: 'MOBITELI',
        brand: 'Apple',
        currentPrice: '1.199,99 €',
        oldPrice: '1.399,99 €',
        image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-naturaltitanium?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692895395658',
        description: 'Najnoviji iPhone 15 Pro s A17 Pro čipom, titanijskim kućištem i naprednim kamerama. Dostupan u različitim bojama s 128GB prostora za pohranu.',
        specs: ['A17 Pro čip', 'Titanijsko kućište', '48MP kamera', '128GB memorija'],
        inStock: true,
        featured: true,
        badge: 'sale',
        badgeText: '-15%'
    },
    'iphone15': {
        id: 'iphone15',
        title: 'iPhone 15 128GB',
        category: 'MOBITELI',
        brand: 'Apple',
        currentPrice: '999,99 €',
        oldPrice: '',
        image: 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-pink?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1692895395658',
        description: 'iPhone 15 s A16 Bionic čipom i Dynamic Island. Odličan izbor za svakodnevnu upotrebu.',
        specs: ['A16 Bionic čip', 'Dynamic Island', '48MP kamera', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxys24': {
        id: 'galaxys24',
        title: 'Samsung Galaxy S24 256GB',
        category: 'MOBITELI',
        brand: 'Samsung',
        currentPrice: '899,99 €',
        oldPrice: '',
        image: 'https://images.samsung.com/is/image/samsung/p6pim/rs/2401/gallery/rs-galaxy-s24-s928-sm-s928bztgeuc-thumb-539573016',
        description: 'Samsung Galaxy S24 s najnovijim Snapdragon procesorom, odličnim kamerama i 256GB prostora.',
        specs: ['Snapdragon 8 Gen 3', '50MP kamera', '256GB memorija', 'AI funkcije'],
        inStock: true,
        featured: true,
        badge: 'new',
        badgeText: 'NOVO'
    },
    'galaxys24ultra': {
        id: 'galaxys24ultra',
        title: 'Samsung Galaxy S24 Ultra 512GB',
        category: 'MOBITELI',
        brand: 'Samsung',
        currentPrice: '1.399,99 €',
        oldPrice: '1.599,99 €',
        image: 'https://images.samsung.com/is/image/samsung/p6pim/rs/2401/gallery/rs-galaxy-s24-ultra-s928-sm-s928bztueuc-thumb-539573025',
        description: 'Vrhunski Galaxy S24 Ultra s S Pen olovkom i 200MP kamerom.',
        specs: ['Snapdragon 8 Gen 3', '200MP kamera', 'S Pen', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'pixel8pro': {
        id: 'pixel8pro',
        title: 'Google Pixel 8 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Google',
        currentPrice: '799,99 €',
        oldPrice: '899,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Google Pixel 8 Pro s Tensor G3 čipom i najnaprednijim AI funkcijama.',
        specs: ['Tensor G3 čip', 'AI fotografija', '50MP kamera', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'oneplus12': {
        id: 'oneplus12',
        title: 'OnePlus 12 256GB',
        category: 'MOBITELI',
        brand: 'OnePlus',
        currentPrice: '849,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'OnePlus 12 s Snapdragon 8 Gen 3 čipom i brzim punjenjem.',
        specs: ['Snapdragon 8 Gen 3', '50MP kamera', '100W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'xiaomi14': {
        id: 'xiaomi14',
        title: 'Xiaomi 14 Pro 512GB',
        category: 'MOBITELI',
        brand: 'Xiaomi',
        currentPrice: '749,99 €',
        oldPrice: '849,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Xiaomi 14 Pro s Leica kamerama i premium dizajnom.',
        specs: ['Snapdragon 8 Gen 3', 'Leica kamere', '120W punjenje', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'huaweip60': {
        id: 'huaweip60',
        title: 'Huawei P60 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Huawei',
        currentPrice: '699,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Huawei P60 Pro s naprednim kamerama i elegantnim dizajnom.',
        specs: ['Kirin 9000S', '48MP kamera', 'Leica optika', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'sonyxperia1v': {
        id: 'sonyxperia1v',
        title: 'Sony Xperia 1 V 256GB',
        category: 'MOBITELI',
        brand: 'Sony',
        currentPrice: '1.199,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Sony Xperia 1 V s profesionalnim kamerama i 4K displayom.',
        specs: ['Snapdragon 8 Gen 2', '4K OLED display', 'Alpha kamere', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'iphone14pro': {
        id: 'iphone14pro',
        title: 'iPhone 14 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Apple',
        currentPrice: '1.099,99 €',
        oldPrice: '1.299,99 €',
        image: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'iPhone 14 Pro s A16 Bionic čipom i Dynamic Island.',
        specs: ['A16 Bionic čip', 'Dynamic Island', '48MP Pro kamera', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxys23ultra': {
        id: 'galaxys23ultra',
        title: 'Samsung Galaxy S23 Ultra 512GB',
        category: 'MOBITELI',
        brand: 'Samsung',
        currentPrice: '1.299,99 €',
        oldPrice: '1.499,99 €',
        image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Galaxy S23 Ultra s 200MP kamerom i S Pen olovkom.',
        specs: ['Snapdragon 8 Gen 2', '200MP kamera', 'S Pen uključen', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'pixel7pro': {
        id: 'pixel7pro',
        title: 'Google Pixel 7 Pro 128GB',
        category: 'MOBITELI',
        brand: 'Google',
        currentPrice: '649,99 €',
        oldPrice: '799,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Google Pixel 7 Pro s Tensor G2 čipom i AI fotografijom.',
        specs: ['Tensor G2 čip', 'AI fotografija', '50MP kamera', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'oneplus11': {
        id: 'oneplus11',
        title: 'OnePlus 11 128GB',
        category: 'MOBITELI',
        brand: 'OnePlus',
        currentPrice: '699,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'OnePlus 11 s Snapdragon 8 Gen 2 i brzim punjenjem.',
        specs: ['Snapdragon 8 Gen 2', '50MP kamera', '100W punjenje', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'xiaomi13pro': {
        id: 'xiaomi13pro',
        title: 'Xiaomi 13 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Xiaomi',
        currentPrice: '799,99 €',
        oldPrice: '899,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Xiaomi 13 Pro s Leica kamerama i premium performansama.',
        specs: ['Snapdragon 8 Gen 2', 'Leica kamere', '120W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'oppofindn3': {
        id: 'oppofindn3',
        title: 'OPPO Find N3 512GB',
        category: 'MOBITELI',
        brand: 'OPPO',
        currentPrice: '1.599,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Sklopivi OPPO Find N3 s Hasselblad kamerama.',
        specs: ['Snapdragon 8 Gen 2', 'Hasselblad kamere', 'Sklopivi dizajn', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'vivox100pro': {
        id: 'vivox100pro',
        title: 'Vivo X100 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Vivo',
        currentPrice: '899,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Vivo X100 Pro s MediaTek Dimensity 9300 čipom.',
        specs: ['MediaTek Dimensity 9300', '50MP kamera', 'Zeiss optika', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'honormagic6pro': {
        id: 'honormagic6pro',
        title: 'Honor Magic6 Pro 512GB',
        category: 'MOBITELI',
        brand: 'Honor',
        currentPrice: '1.099,99 €',
        oldPrice: '1.199,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Honor Magic6 Pro s naprednim AI funkcijama.',
        specs: ['Snapdragon 8 Gen 3', 'AI fotografija', '180MP kamera', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'nothingphone2': {
        id: 'nothingphone2',
        title: 'Nothing Phone (2) 256GB',
        category: 'MOBITELI',
        brand: 'Nothing',
        currentPrice: '649,99 €',
        oldPrice: '699,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Nothing Phone (2) s jedinstvenim Glyph sučeljem.',
        specs: ['Snapdragon 8+ Gen 1', 'Glyph Interface', '50MP kamera', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'realme11pro': {
        id: 'realme11pro',
        title: 'Realme 11 Pro+ 256GB',
        category: 'MOBITELI',
        brand: 'Realme',
        currentPrice: '549,99 €',
        oldPrice: '649,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Realme 11 Pro+ s MediaTek Dimensity 7050 čipom.',
        specs: ['MediaTek Dimensity 7050', '200MP kamera', '100W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'redminotepro': {
        id: 'redminotepro',
        title: 'Redmi Note 13 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Xiaomi',
        currentPrice: '399,99 €',
        oldPrice: '449,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Redmi Note 13 Pro s odličnim omjerom cijene i performansi.',
        specs: ['Snapdragon 7s Gen 2', '200MP kamera', '67W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },

    // LAPTOPI
    'macbookair': {
        id: 'macbookair',
        title: 'MacBook Air M3 13" 256GB',
        category: 'LAPTOPI',
        brand: 'Apple',
        currentPrice: '1.349,99 €',
        oldPrice: '1.499,99 €',
        image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'MacBook Air s M3 čipom pruža nevjerojatnu performansu i bateriju koja traje cijeli dan.',
        specs: ['M3 čip', '13.6" Liquid Retina', '256GB SSD', '18h baterija'],
        inStock: true,
        featured: true,
        badge: 'sale',
        badgeText: '-10%'
    },
    'macbookpro': {
        id: 'macbookpro',
        title: 'MacBook Pro M3 Pro 14" 512GB',
        category: 'LAPTOPI',
        brand: 'Apple',
        currentPrice: '2.199,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Profesionalni MacBook Pro s M3 Pro čipom za zahtjevne zadatke.',
        specs: ['M3 Pro čip', '14.2" Liquid Retina XDR', '512GB SSD', 'ProRes podrška'],
        inStock: true,
        featured: false
    },
    'dellxps13': {
        id: 'dellxps13',
        title: 'Dell XPS 13 Intel i7 512GB',
        category: 'LAPTOPI',
        brand: 'Dell',
        currentPrice: '1.299,99 €',
        oldPrice: '1.499,99 €',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Elegantan Dell XPS 13 s Intel Core i7 procesorom i premium dizajnom.',
        specs: ['Intel Core i7', '13.4" InfinityEdge', '512GB SSD', '16GB RAM'],
        inStock: true,
        featured: false
    },
    'lenovothinkpad': {
        id: 'lenovothinkpad',
        title: 'Lenovo ThinkPad X1 Carbon Gen 11',
        category: 'LAPTOPI',
        brand: 'Lenovo',
        currentPrice: '1.599,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Poslovni laptop s vrhunskim performansama i dugotrajnom baterijom.',
        specs: ['Intel Core i7', '14" WUXGA', '1TB SSD', 'TrackPoint'],
        inStock: true,
        featured: false
    },
    'hpspectre': {
        id: 'hpspectre',
        title: 'HP Spectre x360 14" Intel i7',
        category: 'LAPTOPI',
        brand: 'HP',
        currentPrice: '1.399,99 €',
        oldPrice: '1.599,99 €',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Konvertibilni laptop s OLED displayom i premium dizajnom.',
        specs: ['Intel Core i7', '14" OLED touchscreen', '512GB SSD', '360° okretanje'],
        inStock: true,
        featured: false
    },
    'asuszenbook': {
        id: 'asuszenbook',
        title: 'ASUS ZenBook 14 OLED',
        category: 'LAPTOPI',
        brand: 'ASUS',
        currentPrice: '1.199,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Elegantan ultrabook s OLED displayom i AMD Ryzen procesorom.',
        specs: ['AMD Ryzen 7', '14" OLED 2.8K', '512GB SSD', 'NumberPad 2.0'],
        inStock: true,
        featured: false
    },
    'surfacelaptop': {
        id: 'surfacelaptop',
        title: 'Microsoft Surface Laptop 5 13.5"',
        category: 'LAPTOPI',
        brand: 'Microsoft',
        currentPrice: '1.299,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Premium laptop s touchscreen displayom i Alcantara tipkovnicom.',
        specs: ['Intel Core i7', '13.5" PixelSense', '512GB SSD', 'Alcantara tipkovnica'],
        inStock: true,
        featured: false
    },
    'macbookpro16': {
        id: 'macbookpro16',
        title: 'MacBook Pro M3 Max 16" 1TB',
        category: 'LAPTOPI',
        brand: 'Apple',
        currentPrice: '3.199,99 €',
        oldPrice: '3.499,99 €',
        image: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Najmoćniji MacBook Pro s M3 Max čipom za profesionalce.',
        specs: ['M3 Max čip', '16.2" Liquid Retina XDR', '1TB SSD', '36-core GPU'],
        inStock: true,
        featured: false
    },
    'alienwarex17': {
        id: 'alienwarex17',
        title: 'Alienware x17 R2 RTX 4080',
        category: 'LAPTOPI',
        brand: 'Dell',
        currentPrice: '2.899,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Gaming laptop s RTX 4080 i 360Hz displayom.',
        specs: ['Intel Core i9', 'RTX 4080', '17.3" 360Hz', '1TB SSD'],
        inStock: true,
        featured: false
    },
    'asusrogzephyrus': {
        id: 'asusrogzephyrus',
        title: 'ASUS ROG Zephyrus G16 RTX 4070',
        category: 'LAPTOPI',
        brand: 'ASUS',
        currentPrice: '2.199,99 €',
        oldPrice: '2.399,99 €',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Tanki gaming laptop s RTX 4070 i OLED displayom.',
        specs: ['AMD Ryzen 9', 'RTX 4070', '16" OLED 240Hz', '1TB SSD'],
        inStock: true,
        featured: false
    },
    'lenovoyoga9i': {
        id: 'lenovoyoga9i',
        title: 'Lenovo Yoga 9i 14" 2-in-1',
        category: 'LAPTOPI',
        brand: 'Lenovo',
        currentPrice: '1.699,99 €',
        oldPrice: '1.899,99 €',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Konvertibilni laptop s OLED touchscreen displayom.',
        specs: ['Intel Core i7', '14" OLED touchscreen', '1TB SSD', '360° okretanje'],
        inStock: true,
        featured: false
    },
    'razerblade15': {
        id: 'razerblade15',
        title: 'Razer Blade 15 RTX 4060',
        category: 'LAPTOPI',
        brand: 'Razer',
        currentPrice: '1.999,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Kompaktni gaming laptop s premium dizajnom.',
        specs: ['Intel Core i7', 'RTX 4060', '15.6" QHD 240Hz', '1TB SSD'],
        inStock: true,
        featured: false
    },

    // TABLETI
    'ipadpro': {
        id: 'ipadpro',
        title: 'iPad Pro 11" M4 256GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '1.099,99 €',
        oldPrice: '',
        image: 'https://picsum.photos/400/400?random=1',
        description: 'iPad Pro s M4 čipom i Liquid Retina displayom. Idealan za profesionalce.',
        specs: ['M4 čip', '11" Liquid Retina', 'Apple Pencil podrška', '256GB memorija'],
        inStock: true,
        featured: true,
        badge: 'bestseller',
        badgeText: 'BESTSELLER'
    },
    'ipadair': {
        id: 'ipadair',
        title: 'iPad Air M2 10.9" 128GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '699,99 €',
        oldPrice: '799,99 €',
        image: 'https://picsum.photos/400/400?random=2',
        description: 'iPad Air s M2 čipom - savršen balans performansi i cijene.',
        specs: ['M2 čip', '10.9" Liquid Retina', 'Touch ID', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxytabs9': {
        id: 'galaxytabs9',
        title: 'Samsung Galaxy Tab S9 256GB',
        category: 'TABLETI',
        brand: 'Samsung',
        currentPrice: '899,99 €',
        oldPrice: '',
        image: 'https://picsum.photos/400/400?random=3',
        description: 'Premium Android tablet s S Pen olovkom i AMOLED displayom.',
        specs: ['Snapdragon 8 Gen 2', '11" AMOLED', 'S Pen uključen', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'ipadmini': {
        id: 'ipadmini',
        title: 'iPad mini 6th gen 256GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '649,99 €',
        oldPrice: '749,99 €',
        image: 'https://picsum.photos/400/400?random=4',
        description: 'Kompaktni iPad s A15 Bionic čipom i Apple Pencil podrškom.',
        specs: ['A15 Bionic čip', '8.3" Liquid Retina', 'Apple Pencil 2', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'surfacepro9': {
        id: 'surfacepro9',
        title: 'Microsoft Surface Pro 9 256GB',
        category: 'TABLETI',
        brand: 'Microsoft',
        currentPrice: '1.199,99 €',
        oldPrice: '',
        image: 'https://picsum.photos/400/400?random=5',
        description: '2-u-1 tablet s Intel procesorom i detachable tipkovnicom.',
        specs: ['Intel Core i5', '13" PixelSense', 'Type Cover', '256GB SSD'],
        inStock: true,
        featured: false
    },
    'lenovotab': {
        id: 'lenovotab',
        title: 'Lenovo Tab P12 Pro 256GB',
        category: 'TABLETI',
        brand: 'Lenovo',
        currentPrice: '599,99 €',
        oldPrice: '699,99 €',
        image: 'https://picsum.photos/400/400?random=6',
        description: 'Android tablet s OLED displayom i Precision Pen 3.',
        specs: ['MediaTek Dimensity 9000', '12.6" OLED', 'Precision Pen 3', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'ipadpro129': {
        id: 'ipadpro129',
        title: 'iPad Pro 12.9" M4 512GB',
        category: 'TABLETI',
        brand: 'Apple',
        currentPrice: '1.499,99 €',
        oldPrice: '1.699,99 €',
        image: 'https://picsum.photos/400/400?random=7',
        description: 'Najveći iPad Pro s M4 čipom i Liquid Retina XDR displayom.',
        specs: ['M4 čip', '12.9" Liquid Retina XDR', 'Apple Pencil Pro', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'galaxytabs9ultra': {
        id: 'galaxytabs9ultra',
        title: 'Samsung Galaxy Tab S9 Ultra 512GB',
        category: 'TABLETI',
        brand: 'Samsung',
        currentPrice: '1.299,99 €',
        oldPrice: '',
        image: 'https://picsum.photos/400/400?random=8',
        description: 'Najveći Galaxy tablet s 14.6" AMOLED displayom.',
        specs: ['Snapdragon 8 Gen 2', '14.6" AMOLED', 'S Pen uključen', '512GB memorija'],
        inStock: true,
        featured: false
    },
    'surfacepro10': {
        id: 'surfacepro10',
        title: 'Microsoft Surface Pro 10 512GB',
        category: 'TABLETI',
        brand: 'Microsoft',
        currentPrice: '1.599,99 €',
        oldPrice: '',
        image: 'https://picsum.photos/400/400?random=9',
        description: 'Najnoviji Surface Pro s Intel Core Ultra procesorom.',
        specs: ['Intel Core Ultra 7', '13" PixelSense Flow', 'Type Cover Pro', '512GB SSD'],
        inStock: true,
        featured: false
    },

    // GAMING
    'ps5': {
        id: 'ps5',
        title: 'PlayStation 5 Console',
        category: 'GAMING',
        brand: 'Sony',
        currentPrice: '549,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Najnovija PlayStation 5 konzola s ultra-brzim SSD-om.',
        specs: ['Custom AMD Zen 2', '825GB SSD', '4K gaming', 'Ray tracing'],
        inStock: true,
        featured: false
    },
    'xboxseriesx': {
        id: 'xboxseriesx',
        title: 'Xbox Series X Console',
        category: 'GAMING',
        brand: 'Microsoft',
        currentPrice: '499,99 €',
        oldPrice: '549,99 €',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Moćna Xbox Series X konzola za 4K gaming.',
        specs: ['Custom AMD Zen 2', '1TB SSD', '4K 120fps', 'Quick Resume'],
        inStock: true,
        featured: false
    },
    'steamdeck': {
        id: 'steamdeck',
        title: 'Steam Deck 512GB',
        category: 'GAMING',
        brand: 'Valve',
        currentPrice: '679,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Prijenosna gaming konzola s pristupom Steam biblioteci.',
        specs: ['AMD APU', '7" touchscreen', '512GB SSD', 'SteamOS'],
        inStock: true,
        featured: false
    },
    'nintendoswitch': {
        id: 'nintendoswitch',
        title: 'Nintendo Switch OLED 64GB',
        category: 'GAMING',
        brand: 'Nintendo',
        currentPrice: '349,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Hibridna gaming konzola s OLED displayom.',
        specs: ['NVIDIA Tegra X1', '7" OLED touchscreen', '64GB memorija', 'Joy-Con kontroleri'],
        inStock: true,
        featured: false
    },
    'asusrog': {
        id: 'asusrog',
        title: 'ASUS ROG Ally Z1 Extreme',
        category: 'GAMING',
        brand: 'ASUS',
        currentPrice: '799,99 €',
        oldPrice: '899,99 €',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Windows gaming handheld s AMD Z1 Extreme čipom.',
        specs: ['AMD Z1 Extreme', '7" FHD 120Hz', '512GB SSD', 'Windows 11'],
        inStock: true,
        featured: false
    },
    'logitechg923': {
        id: 'logitechg923',
        title: 'Logitech G923 Racing Wheel',
        category: 'GAMING',
        brand: 'Logitech',
        currentPrice: '399,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Profesionalni racing volan s TRUEFORCE tehnologijom.',
        specs: ['TRUEFORCE feedback', 'Dual clutch', 'Leather wrap', 'PS5/Xbox/PC kompatibilnost'],
        inStock: true,
        featured: false
    },

    // DODACI
    'airpodspro': {
        id: 'airpodspro',
        title: 'Apple AirPods Pro (3rd gen)',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '279,99 €',
        oldPrice: '329,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Bežične slušalice s aktivnim poništavanjem buke.',
        specs: ['Active Noise Cancellation', 'Spatial Audio', 'H2 čip', 'MagSafe punjenje'],
        inStock: true,
        featured: false
    },
    'applewatch': {
        id: 'applewatch',
        title: 'Apple Watch Series 9 45mm',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '449,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Najnapredniji Apple Watch s S9 čipom.',
        specs: ['S9 SiP čip', '45mm Always-On Retina', 'GPS + Cellular', 'Zdravstveni senzori'],
        inStock: true,
        featured: false
    },
    'magickeyboard': {
        id: 'magickeyboard',
        title: 'Apple Magic Keyboard',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '119,99 €',
        oldPrice: '139,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Bežična tipkovnica s Touch ID senzorem.',
        specs: ['Touch ID', 'Bežična povezanost', 'Punjiva baterija', 'Scissor mehanizam'],
        inStock: true,
        featured: false
    },
    'magicmouse': {
        id: 'magicmouse',
        title: 'Apple Magic Mouse',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '89,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Bežični miš s Multi-Touch površinom.',
        specs: ['Multi-Touch površina', 'Bežična povezanost', 'Punjiva baterija', 'Ergonomski dizajn'],
        inStock: true,
        featured: false
    },
    'samsungbuds': {
        id: 'samsungbuds',
        title: 'Samsung Galaxy Buds2 Pro',
        category: 'DODACI',
        brand: 'Samsung',
        currentPrice: '199,99 €',
        oldPrice: '229,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Premium bežične slušalice s ANC tehnologijom.',
        specs: ['Active Noise Cancellation', '360 Audio', 'IPX7 otpornost', 'Bežično punjenje'],
        inStock: true,
        featured: false
    },
    'logitechmx': {
        id: 'logitechmx',
        title: 'Logitech MX Master 3S',
        category: 'DODACI',
        brand: 'Logitech',
        currentPrice: '109,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Profesionalni bežični miš za produktivnost.',
        specs: ['4000 DPI senzor', 'USB-C punjenje', 'Multi-device', 'Ergonomski dizajn'],
        inStock: true,
        featured: false
    },
    'ankercharger': {
        id: 'ankercharger',
        title: 'Anker PowerPort III 65W',
        category: 'DODACI',
        brand: 'Anker',
        currentPrice: '49,99 €',
        oldPrice: '59,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Brzi USB-C punjač za laptop i mobitel.',
        specs: ['65W izlaz', 'GaN tehnologija', 'USB-C PD', 'Kompaktni dizajn'],
        inStock: true,
        featured: false
    },
    'belkinstand': {
        id: 'belkinstand',
        title: 'Belkin MagSafe 3-in-1 Charger',
        category: 'DODACI',
        brand: 'Belkin',
        currentPrice: '149,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Bežični punjač za iPhone, Apple Watch i AirPods.',
        specs: ['MagSafe kompatibilnost', '15W bežično punjenje', 'Apple Watch punjač', 'AirPods punjač'],
        inStock: true,
        featured: false
    },
    'usbchub': {
        id: 'usbchub',
        title: 'USB-C Hub 7-in-1',
        category: 'DODACI',
        brand: 'HyperDrive',
        currentPrice: '79,99 €',
        oldPrice: '99,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Multifunkcionalni USB-C hub s 7 portova.',
        specs: ['7 portova', '4K HDMI izlaz', 'USB 3.0', 'SD card čitač'],
        inStock: true,
        featured: false
    },
    'webcam4k': {
        id: 'webcam4k',
        title: 'Logitech Brio 4K Webcam',
        category: 'DODACI',
        brand: 'Logitech',
        currentPrice: '199,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: '4K Ultra HD webcam za profesionalne video pozive.',
        specs: ['4K Ultra HD', 'HDR podrška', 'Auto focus', 'Windows Hello'],
        inStock: true,
        featured: false
    },
    'portablessd': {
        id: 'portablessd',
        title: 'Samsung T7 Portable SSD 1TB',
        category: 'DODACI',
        brand: 'Samsung',
        currentPrice: '129,99 €',
        oldPrice: '149,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Brzi prijenosni SSD s USB 3.2 sučeljem.',
        specs: ['1TB kapacitet', '1050 MB/s brzina', 'USB 3.2 Gen 2', 'Kompaktni dizajn'],
        inStock: true,
        featured: false
    },
    'bluetoothspeaker': {
        id: 'bluetoothspeaker',
        title: 'JBL Charge 5 Bluetooth Speaker',
        category: 'DODACI',
        brand: 'JBL',
        currentPrice: '179,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Vodootporni Bluetooth zvučnik s powerbank funkcijom.',
        specs: ['IP67 otpornost', '20h baterija', 'Powerbank funkcija', 'JBL Pro Sound'],
        inStock: true,
        featured: false
    },
    'applepen': {
        id: 'applepen',
        title: 'Apple Pencil (2nd generation)',
        category: 'DODACI',
        brand: 'Apple',
        currentPrice: '139,99 €',
        oldPrice: '149,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Precizna olovka za iPad s magnetskim punjenjem.',
        specs: ['Magnetsko punjenje', 'Pixel-perfect preciznost', 'Tilt i pressure senzori', 'Double-tap funkcija'],
        inStock: true,
        featured: false
    },
    'sonyheadphones': {
        id: 'sonyheadphones',
        title: 'Sony WH-1000XM5 Headphones',
        category: 'DODACI',
        brand: 'Sony',
        currentPrice: '399,99 €',
        oldPrice: '449,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Premium noise-cancelling slušalice s 30h baterijom.',
        specs: ['Industry-leading ANC', '30h baterija', 'LDAC codec', 'Multipoint povezivanje'],
        inStock: true,
        featured: false
    },
    'razerdeathstalker': {
        id: 'razerdeathstalker',
        title: 'Razer DeathStalker V2 Pro',
        category: 'DODACI',
        brand: 'Razer',
        currentPrice: '249,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Bežična gaming tipkovnica s low-profile switchevima.',
        specs: ['Low-profile optical switches', 'HyperSpeed Wireless', '90h baterija', 'RGB Chroma'],
        inStock: true,
        featured: false
    },
    'corsairram': {
        id: 'corsairram',
        title: 'Corsair Vengeance LPX 32GB DDR4',
        category: 'DODACI',
        brand: 'Corsair',
        currentPrice: '129,99 €',
        oldPrice: '159,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'High-performance DDR4 memorija za gaming i rad.',
        specs: ['32GB (2x16GB)', 'DDR4-3200', 'Low profile design', 'XMP 2.0 podrška'],
        inStock: true,
        featured: false
    },
    'nvidiartx4070': {
        id: 'nvidiartx4070',
        title: 'NVIDIA GeForce RTX 4070 12GB',
        category: 'DODACI',
        brand: 'NVIDIA',
        currentPrice: '649,99 €',
        oldPrice: '699,99 €',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Moćna grafička kartica za 1440p gaming i kreativnost.',
        specs: ['Ada Lovelace arhitektura', '12GB GDDR6X', 'DLSS 3', 'Ray Tracing 3rd gen'],
        inStock: true,
        featured: false
    },
    'monitorlg': {
        id: 'monitorlg',
        title: 'LG UltraGear 27" 4K Gaming Monitor',
        category: 'DODACI',
        brand: 'LG',
        currentPrice: '599,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: '4K gaming monitor s 144Hz refresh rate i HDR600.',
        specs: ['27" 4K IPS', '144Hz refresh rate', 'HDR600', 'G-Sync Compatible'],
        inStock: true,
        featured: false
    },

    // Dodatni MOBITELI
    'motorolaedge40': {
        id: 'motorolaedge40',
        title: 'Motorola Edge 40 Pro 256GB',
        category: 'MOBITELI',
        brand: 'Motorola',
        currentPrice: '599,99 €',
        oldPrice: '699,99 €',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Motorola Edge 40 Pro s Snapdragon 8 Gen 2 čipom.',
        specs: ['Snapdragon 8 Gen 2', '50MP kamera', '125W punjenje', '256GB memorija'],
        inStock: true,
        featured: false
    },
    'fairphone5': {
        id: 'fairphone5',
        title: 'Fairphone 5 256GB',
        category: 'MOBITELI',
        brand: 'Fairphone',
        currentPrice: '699,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Održivi smartphone s modularnim dizajnom.',
        specs: ['QCM6490 čip', '50MP kamera', 'Modularan dizajn', '256GB memorija'],
        inStock: true,
        featured: false
    },

    // Dodatni LAPTOPI
    'frameworklaptop': {
        id: 'frameworklaptop',
        title: 'Framework Laptop 13" Intel i7',
        category: 'LAPTOPI',
        brand: 'Framework',
        currentPrice: '1.399,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Modularan laptop koji možete sami popraviti i nadograditi.',
        specs: ['Intel Core i7', '13.5" 2256x1504', 'Modularni portovi', '512GB SSD'],
        inStock: true,
        featured: false
    },
    'steamdeckoled': {
        id: 'steamdeckoled',
        title: 'Steam Deck 512GB OLED',
        category: 'GAMING',
        brand: 'Valve',
        currentPrice: '679,99 €',
        oldPrice: '',
        image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=400',
        description: 'Prijenosna gaming konzola s OLED displayom.',
        specs: ['AMD APU', '7.4" OLED HDR', 'SteamOS', '512GB NVMe'],
        inStock: true,
        featured: true,
        badge: 'new',
        badgeText: 'NOVO'
    },

    // Dodatni TABLETI
    'galaxytaba9': {
        id: 'galaxytaba9',
        title: 'Samsung Galaxy Tab A9+ 128GB',
        category: 'TABLETI',
        brand: 'Samsung',
        currentPrice: '299,99 €',
        oldPrice: '349,99 €',
        image: 'https://picsum.photos/400/400?random=10',
        description: 'Pristupačan Android tablet za svakodnevnu upotrebu.',
        specs: ['Helio G99', '11" LCD', 'Quad speakers', '128GB memorija'],
        inStock: true,
        featured: false
    },
    'huaweimatepadt11': {
        id: 'huaweimatepadt11',
        title: 'Huawei MatePad T11 128GB',
        category: 'TABLETI',
        brand: 'Huawei',
        currentPrice: '249,99 €',
        oldPrice: '',
        image: 'https://picsum.photos/400/400?random=11',
        description: 'Huawei tablet s HarmonyOS sustavom.',
        specs: ['Snapdragon 662', '10.95" IPS', 'HarmonyOS', '128GB memorija'],
        inStock: true,
        featured: false
    }
};

// Helper functions
function getProductsByCategory(category) {
    return Object.values(PRODUCT_DATABASE).filter(product =>
        product.category === category.toUpperCase()
    );
}

function getFeaturedProducts() {
    return Object.values(PRODUCT_DATABASE).filter(product => product.featured);
}

function searchProducts(searchTerm) {
    const term = searchTerm.toLowerCase();
    return Object.values(PRODUCT_DATABASE).filter(product =>
        product.title.toLowerCase().includes(term) ||
        product.description.toLowerCase().includes(term) ||
        product.brand.toLowerCase().includes(term) ||
        product.category.toLowerCase().includes(term)
    );
}

function getProductById(id) {
    return PRODUCT_DATABASE[id] || null;
}

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        PRODUCT_DATABASE,
        getProductsByCategory,
        getFeaturedProducts,
        searchProducts,
        getProductById
    };
}
